// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
using Vorn.Tamin.Kiota.Sandbox.Auth.Server;
using Vorn.Tamin.Kiota.Sandbox.Auth.Signout;
namespace Vorn.Tamin.Kiota.Sandbox.Auth
{
    /// <summary>
    /// Builds and executes requests for operations under \auth
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class AuthRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The server property</summary>
        public global::Vorn.Tamin.Kiota.Sandbox.Auth.Server.ServerRequestBuilder Server
        {
            get => new global::Vorn.Tamin.Kiota.Sandbox.Auth.Server.ServerRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The signout property</summary>
        public global::Vorn.Tamin.Kiota.Sandbox.Auth.Signout.SignoutRequestBuilder Signout
        {
            get => new global::Vorn.Tamin.Kiota.Sandbox.Auth.Signout.SignoutRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Vorn.Tamin.Kiota.Sandbox.Auth.AuthRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public AuthRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/auth", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Vorn.Tamin.Kiota.Sandbox.Auth.AuthRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public AuthRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/auth", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
