// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
using Vorn.Tamin.Kiota.Interface.Epresc.SendEpresc.V2.PatientNoteDetailsReferral.Count;
namespace Vorn.Tamin.Kiota.Interface.Epresc.SendEpresc.V2.PatientNoteDetailsReferral
{
    /// <summary>
    /// Builds and executes requests for operations under \interface\epresc\SendEpresc\v2\patientNoteDetailsReferral
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class PatientNoteDetailsReferralRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The count property</summary>
        public global::Vorn.Tamin.Kiota.Interface.Epresc.SendEpresc.V2.PatientNoteDetailsReferral.Count.CountRequestBuilder Count
        {
            get => new global::Vorn.Tamin.Kiota.Interface.Epresc.SendEpresc.V2.PatientNoteDetailsReferral.Count.CountRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Vorn.Tamin.Kiota.Interface.Epresc.SendEpresc.V2.PatientNoteDetailsReferral.PatientNoteDetailsReferralRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public PatientNoteDetailsReferralRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/interface/epresc/SendEpresc/v2/patientNoteDetailsReferral", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Vorn.Tamin.Kiota.Interface.Epresc.SendEpresc.V2.PatientNoteDetailsReferral.PatientNoteDetailsReferralRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public PatientNoteDetailsReferralRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/interface/epresc/SendEpresc/v2/patientNoteDetailsReferral", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
