// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
using Vorn.Tamin.Kiota.Sandbox.Api.NoteDetailsReferral.Forward;
using Vorn.Tamin.Kiota.Sandbox.Api.NoteDetailsReferral.Noteheads;
namespace Vorn.Tamin.Kiota.Sandbox.Api.NoteDetailsReferral
{
    /// <summary>
    /// Builds and executes requests for operations under \api\noteDetailsReferral
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class NoteDetailsReferralRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The forward property</summary>
        public global::Vorn.Tamin.Kiota.Sandbox.Api.NoteDetailsReferral.Forward.ForwardRequestBuilder Forward
        {
            get => new global::Vorn.Tamin.Kiota.Sandbox.Api.NoteDetailsReferral.Forward.ForwardRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The noteheads property</summary>
        public global::Vorn.Tamin.Kiota.Sandbox.Api.NoteDetailsReferral.Noteheads.NoteheadsRequestBuilder Noteheads
        {
            get => new global::Vorn.Tamin.Kiota.Sandbox.Api.NoteDetailsReferral.Noteheads.NoteheadsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Vorn.Tamin.Kiota.Sandbox.Api.NoteDetailsReferral.NoteDetailsReferralRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public NoteDetailsReferralRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/noteDetailsReferral", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Vorn.Tamin.Kiota.Sandbox.Api.NoteDetailsReferral.NoteDetailsReferralRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public NoteDetailsReferralRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/noteDetailsReferral", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
