// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
using Vorn.Tamin.Kiota.Sandbox.Api.CartablenoteDetailsReferral.Item.Item;
namespace Vorn.Tamin.Kiota.Sandbox.Api.CartablenoteDetailsReferral.Item
{
    /// <summary>
    /// Builds and executes requests for operations under \api\cartablenoteDetailsReferral\{docNationalCode}
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class WithDocNationalCodeItemRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the Vorn.Tamin.Kiota.Sandbox.api.cartablenoteDetailsReferral.item.item collection</summary>
        /// <param name="position">Patient national code</param>
        /// <returns>A <see cref="global::Vorn.Tamin.Kiota.Sandbox.Api.CartablenoteDetailsReferral.Item.Item.WithPatientNationalCodeItemRequestBuilder"/></returns>
        public global::Vorn.Tamin.Kiota.Sandbox.Api.CartablenoteDetailsReferral.Item.Item.WithPatientNationalCodeItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("patientNationalCode", position);
                return new global::Vorn.Tamin.Kiota.Sandbox.Api.CartablenoteDetailsReferral.Item.Item.WithPatientNationalCodeItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Vorn.Tamin.Kiota.Sandbox.Api.CartablenoteDetailsReferral.Item.WithDocNationalCodeItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithDocNationalCodeItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/cartablenoteDetailsReferral/{docNationalCode}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Vorn.Tamin.Kiota.Sandbox.Api.CartablenoteDetailsReferral.Item.WithDocNationalCodeItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithDocNationalCodeItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/cartablenoteDetailsReferral/{docNationalCode}", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
