using Vorn.Tamin.Kiota;

namespace Vorn.Tamin;

/// <summary>
/// Represents identity operations; no identity provider paths are exposed because none are generated by the Kiota client.
/// </summary>
public sealed class IdentityClient
{
    internal IdentityClient(ITaminKiotaGateway gateway)
    {
        ArgumentNullException.ThrowIfNull(gateway);
    }
}
