// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
using Vorn.Tamin.Kiota.Interface.Epresc.Patient.V2.DeserveInfo.Item;
namespace Vorn.Tamin.Kiota.Interface.Epresc.Patient.V2.DeserveInfo
{
    /// <summary>
    /// Builds and executes requests for operations under \interface\epresc\patient\v2\deserve-info
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class DeserveInfoRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the Vorn.Tamin.Kiota.interface.epresc.patient.v2.deserveInfo.item collection</summary>
        /// <param name="position">Clinic SIAM ID or doctor medical council number when used in office</param>
        /// <returns>A <see cref="global::Vorn.Tamin.Kiota.Interface.Epresc.Patient.V2.DeserveInfo.Item.WithSiamItemRequestBuilder"/></returns>
        public global::Vorn.Tamin.Kiota.Interface.Epresc.Patient.V2.DeserveInfo.Item.WithSiamItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("siamId", position);
                return new global::Vorn.Tamin.Kiota.Interface.Epresc.Patient.V2.DeserveInfo.Item.WithSiamItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Vorn.Tamin.Kiota.Interface.Epresc.Patient.V2.DeserveInfo.DeserveInfoRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public DeserveInfoRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/interface/epresc/patient/v2/deserve-info", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Vorn.Tamin.Kiota.Interface.Epresc.Patient.V2.DeserveInfo.DeserveInfoRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public DeserveInfoRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/interface/epresc/patient/v2/deserve-info", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
