<Project>
    <PropertyGroup>
        <Authors>EP.Tamin.NET Contributors</Authors>
        <Company>EP.Tamin.NET</Company>
        <Copyright>Copyright © EP.Tamin.NET Contributors</Copyright>
        <RepositoryUrl>https://github.com/mobinseven/EP.Tamin.NET</RepositoryUrl>
        <RepositoryType>git</RepositoryType>
        <LangVersion>latest</LangVersion>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <TreatWarningsAsErrors Condition="'$(Configuration)' == 'Release'">true</TreatWarningsAsErrors>
    </PropertyGroup>

</Project>
