// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
using Vorn.Tamin.Kiota.Sandbox.Models;
namespace Vorn.Tamin.Kiota.Sandbox.Api.V2.WsServices
{
    /// <summary>
    /// Builds and executes requests for operations under \api\v2\ws-services
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class WsServicesRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::Vorn.Tamin.Kiota.Sandbox.Api.V2.WsServices.WsServicesRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WsServicesRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/v2/ws-services?serviceType={serviceType}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Vorn.Tamin.Kiota.Sandbox.Api.V2.WsServices.WsServicesRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WsServicesRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/v2/ws-services?serviceType={serviceType}", rawUrl)
        {
        }
        /// <summary>
        /// List services by service type
        /// </summary>
        /// <returns>A List&lt;global::Vorn.Tamin.Kiota.Sandbox.Models.Service&gt;</returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Vorn.Tamin.Kiota.Sandbox.Models.ErrorResponse">When receiving a 401 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<List<global::Vorn.Tamin.Kiota.Sandbox.Models.Service>?> GetAsync(Action<RequestConfiguration<global::Vorn.Tamin.Kiota.Sandbox.Api.V2.WsServices.WsServicesRequestBuilder.WsServicesRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<List<global::Vorn.Tamin.Kiota.Sandbox.Models.Service>> GetAsync(Action<RequestConfiguration<global::Vorn.Tamin.Kiota.Sandbox.Api.V2.WsServices.WsServicesRequestBuilder.WsServicesRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "401", global::Vorn.Tamin.Kiota.Sandbox.Models.ErrorResponse.CreateFromDiscriminatorValue },
            };
            var collectionResult = await RequestAdapter.SendCollectionAsync<global::Vorn.Tamin.Kiota.Sandbox.Models.Service>(requestInfo, global::Vorn.Tamin.Kiota.Sandbox.Models.Service.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
            return collectionResult?.AsList();
        }
        /// <summary>
        /// List services by service type
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Vorn.Tamin.Kiota.Sandbox.Api.V2.WsServices.WsServicesRequestBuilder.WsServicesRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Vorn.Tamin.Kiota.Sandbox.Api.V2.WsServices.WsServicesRequestBuilder.WsServicesRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Vorn.Tamin.Kiota.Sandbox.Api.V2.WsServices.WsServicesRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Vorn.Tamin.Kiota.Sandbox.Api.V2.WsServices.WsServicesRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Vorn.Tamin.Kiota.Sandbox.Api.V2.WsServices.WsServicesRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// List services by service type
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class WsServicesRequestBuilderGetQueryParameters 
        {
            /// <summary>Service type code, e.g. 01, 02, 17</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("serviceType")]
            public string? ServiceType { get; set; }
#nullable restore
#else
            [QueryParameter("serviceType")]
            public string ServiceType { get; set; }
#endif
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class WsServicesRequestBuilderGetRequestConfiguration : RequestConfiguration<global::Vorn.Tamin.Kiota.Sandbox.Api.V2.WsServices.WsServicesRequestBuilder.WsServicesRequestBuilderGetQueryParameters>
        {
        }
    }
}
#pragma warning restore CS0618
