// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
using Vorn.Tamin.Kiota.Sandbox.Api.CartablenoteDetailsReferral;
using Vorn.Tamin.Kiota.Sandbox.Api.Complaint;
using Vorn.Tamin.Kiota.Sandbox.Api.Icd10;
using Vorn.Tamin.Kiota.Sandbox.Api.NoteDetailsReferral;
using Vorn.Tamin.Kiota.Sandbox.Api.Specials;
using Vorn.Tamin.Kiota.Sandbox.Api.V2;
namespace Vorn.Tamin.Kiota.Sandbox.Api
{
    /// <summary>
    /// Builds and executes requests for operations under \api
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ApiRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The cartablenoteDetailsReferral property</summary>
        public global::Vorn.Tamin.Kiota.Sandbox.Api.CartablenoteDetailsReferral.CartablenoteDetailsReferralRequestBuilder CartablenoteDetailsReferral
        {
            get => new global::Vorn.Tamin.Kiota.Sandbox.Api.CartablenoteDetailsReferral.CartablenoteDetailsReferralRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The complaint property</summary>
        public global::Vorn.Tamin.Kiota.Sandbox.Api.Complaint.ComplaintRequestBuilder Complaint
        {
            get => new global::Vorn.Tamin.Kiota.Sandbox.Api.Complaint.ComplaintRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The icd10 property</summary>
        public global::Vorn.Tamin.Kiota.Sandbox.Api.Icd10.Icd10RequestBuilder Icd10
        {
            get => new global::Vorn.Tamin.Kiota.Sandbox.Api.Icd10.Icd10RequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The noteDetailsReferral property</summary>
        public global::Vorn.Tamin.Kiota.Sandbox.Api.NoteDetailsReferral.NoteDetailsReferralRequestBuilder NoteDetailsReferral
        {
            get => new global::Vorn.Tamin.Kiota.Sandbox.Api.NoteDetailsReferral.NoteDetailsReferralRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The specials property</summary>
        public global::Vorn.Tamin.Kiota.Sandbox.Api.Specials.SpecialsRequestBuilder Specials
        {
            get => new global::Vorn.Tamin.Kiota.Sandbox.Api.Specials.SpecialsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The v2 property</summary>
        public global::Vorn.Tamin.Kiota.Sandbox.Api.V2.V2RequestBuilder V2
        {
            get => new global::Vorn.Tamin.Kiota.Sandbox.Api.V2.V2RequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Vorn.Tamin.Kiota.Sandbox.Api.ApiRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ApiRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Vorn.Tamin.Kiota.Sandbox.Api.ApiRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ApiRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
