// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
using Vorn.Tamin.Kiota.Interface.Epresc.SendEpresc.V2.Item.Item.Item.ReferentialPrescDetail;
namespace Vorn.Tamin.Kiota.Interface.Epresc.SendEpresc.V2.Item.Item.Item
{
    /// <summary>
    /// Builds and executes requests for operations under \interface\epresc\SendEpresc\v2\{header-id}\{docId}\{trackingCode}
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class WithTrackingCodeItemRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The referentialPrescDetail property</summary>
        public global::Vorn.Tamin.Kiota.Interface.Epresc.SendEpresc.V2.Item.Item.Item.ReferentialPrescDetail.ReferentialPrescDetailRequestBuilder ReferentialPrescDetail
        {
            get => new global::Vorn.Tamin.Kiota.Interface.Epresc.SendEpresc.V2.Item.Item.Item.ReferentialPrescDetail.ReferentialPrescDetailRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Vorn.Tamin.Kiota.Interface.Epresc.SendEpresc.V2.Item.Item.Item.WithTrackingCodeItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithTrackingCodeItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/interface/epresc/SendEpresc/v2/{header%2Did}/{docId}/{trackingCode}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Vorn.Tamin.Kiota.Interface.Epresc.SendEpresc.V2.Item.Item.Item.WithTrackingCodeItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithTrackingCodeItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/interface/epresc/SendEpresc/v2/{header%2Did}/{docId}/{trackingCode}", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
