// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Vorn.Tamin.Kiota.Sandbox.Auth.Server.Authorize
{
    /// <summary>
    /// Builds and executes requests for operations under \auth\server\authorize
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class AuthorizeRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::Vorn.Tamin.Kiota.Sandbox.Auth.Server.Authorize.AuthorizeRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public AuthorizeRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/auth/server/authorize?client_id={client_id}&code_challenge={code_challenge}&code_challenge_method={code_challenge_method}&redirect_uri={redirect_uri}&response_type={response_type}{&state*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Vorn.Tamin.Kiota.Sandbox.Auth.Server.Authorize.AuthorizeRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public AuthorizeRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/auth/server/authorize?client_id={client_id}&code_challenge={code_challenge}&code_challenge_method={code_challenge_method}&redirect_uri={redirect_uri}&response_type={response_type}{&state*}", rawUrl)
        {
        }
        /// <summary>
        /// Request authorization code
        /// </summary>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task GetAsync(Action<RequestConfiguration<global::Vorn.Tamin.Kiota.Sandbox.Auth.Server.Authorize.AuthorizeRequestBuilder.AuthorizeRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task GetAsync(Action<RequestConfiguration<global::Vorn.Tamin.Kiota.Sandbox.Auth.Server.Authorize.AuthorizeRequestBuilder.AuthorizeRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            await RequestAdapter.SendNoContentAsync(requestInfo, default, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Request authorization code
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Vorn.Tamin.Kiota.Sandbox.Auth.Server.Authorize.AuthorizeRequestBuilder.AuthorizeRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Vorn.Tamin.Kiota.Sandbox.Auth.Server.Authorize.AuthorizeRequestBuilder.AuthorizeRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "text/html");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Vorn.Tamin.Kiota.Sandbox.Auth.Server.Authorize.AuthorizeRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Vorn.Tamin.Kiota.Sandbox.Auth.Server.Authorize.AuthorizeRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Vorn.Tamin.Kiota.Sandbox.Auth.Server.Authorize.AuthorizeRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Request authorization code
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class AuthorizeRequestBuilderGetQueryParameters 
        {
            /// <summary>Client identifier</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("client_id")]
            public string? ClientId { get; set; }
#nullable restore
#else
            [QueryParameter("client_id")]
            public string ClientId { get; set; }
#endif
            /// <summary>BASE64URL-ENCODE(SHA256(ASCII(code_verifier)))</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("code_challenge")]
            public string? CodeChallenge { get; set; }
#nullable restore
#else
            [QueryParameter("code_challenge")]
            public string CodeChallenge { get; set; }
#endif
            /// <summary>Must be S256</summary>
            [Obsolete("This property is deprecated, use CodeChallengeMethodAsGetCodeChallengeMethodQueryParameterType instead")]
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("code_challenge_method")]
            public string? CodeChallengeMethod { get; set; }
#nullable restore
#else
            [QueryParameter("code_challenge_method")]
            public string CodeChallengeMethod { get; set; }
#endif
            /// <summary>Must be S256</summary>
            [QueryParameter("code_challenge_method")]
            public global::Vorn.Tamin.Kiota.Sandbox.Auth.Server.Authorize.GetCode_challenge_methodQueryParameterType? CodeChallengeMethodAsGetCodeChallengeMethodQueryParameterType { get; set; }
            /// <summary>Return URL</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("redirect_uri")]
            public string? RedirectUri { get; set; }
#nullable restore
#else
            [QueryParameter("redirect_uri")]
            public string RedirectUri { get; set; }
#endif
            /// <summary>Must be code</summary>
            [Obsolete("This property is deprecated, use ResponseTypeAsGetResponseTypeQueryParameterType instead")]
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("response_type")]
            public string? ResponseType { get; set; }
#nullable restore
#else
            [QueryParameter("response_type")]
            public string ResponseType { get; set; }
#endif
            /// <summary>Must be code</summary>
            [QueryParameter("response_type")]
            public global::Vorn.Tamin.Kiota.Sandbox.Auth.Server.Authorize.GetResponse_typeQueryParameterType? ResponseTypeAsGetResponseTypeQueryParameterType { get; set; }
            /// <summary>Opaque client state echoed in redirect</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("state")]
            public string? State { get; set; }
#nullable restore
#else
            [QueryParameter("state")]
            public string State { get; set; }
#endif
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class AuthorizeRequestBuilderGetRequestConfiguration : RequestConfiguration<global::Vorn.Tamin.Kiota.Sandbox.Auth.Server.Authorize.AuthorizeRequestBuilder.AuthorizeRequestBuilderGetQueryParameters>
        {
        }
    }
}
#pragma warning restore CS0618
