// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
using Vorn.Tamin.Kiota.Interface.Epresc.Patient.V2.DeserveInfo.Item.Item;
namespace Vorn.Tamin.Kiota.Interface.Epresc.Patient.V2.DeserveInfo.Item
{
    /// <summary>
    /// Builds and executes requests for operations under \interface\epresc\patient\v2\deserve-info\{siamId}
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class WithSiamItemRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the Vorn.Tamin.Kiota.interface.epresc.patient.v2.deserveInfo.item.item collection</summary>
        /// <param name="position">Doctor medical council code</param>
        /// <returns>A <see cref="global::Vorn.Tamin.Kiota.Interface.Epresc.Patient.V2.DeserveInfo.Item.Item.WithDocItemRequestBuilder"/></returns>
        public global::Vorn.Tamin.Kiota.Interface.Epresc.Patient.V2.DeserveInfo.Item.Item.WithDocItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("docId", position);
                return new global::Vorn.Tamin.Kiota.Interface.Epresc.Patient.V2.DeserveInfo.Item.Item.WithDocItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Vorn.Tamin.Kiota.Interface.Epresc.Patient.V2.DeserveInfo.Item.WithSiamItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithSiamItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/interface/epresc/patient/v2/deserve-info/{siamId}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Vorn.Tamin.Kiota.Interface.Epresc.Patient.V2.DeserveInfo.Item.WithSiamItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithSiamItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/interface/epresc/patient/v2/deserve-info/{siamId}", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
