// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Vorn.Tamin.Kiota.Sandbox.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class NoteDetailEprsc : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The dateDo property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? DateDo { get; set; }
#nullable restore
#else
        public string DateDo { get; set; }
#endif
        /// <summary>The dose property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Dose { get; set; }
#nullable restore
#else
        public string Dose { get; set; }
#endif
        /// <summary>The drugInstruction property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Vorn.Tamin.Kiota.Sandbox.Models.DrugInstruction? DrugInstruction { get; set; }
#nullable restore
#else
        public global::Vorn.Tamin.Kiota.Sandbox.Models.DrugInstruction DrugInstruction { get; set; }
#endif
        /// <summary>Physiotherapy illness ID; multiple values comma-separated.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? IllnessId { get; set; }
#nullable restore
#else
        public string IllnessId { get; set; }
#endif
        /// <summary>The isDentalService property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Vorn.Tamin.Kiota.Sandbox.Models.NoteDetailEprsc.NoteDetailEprsc_isDentalService? IsDentalService { get; set; }
#nullable restore
#else
        public global::Vorn.Tamin.Kiota.Sandbox.Models.NoteDetailEprsc.NoteDetailEprsc_isDentalService IsDentalService { get; set; }
#endif
        /// <summary>The PDF table says integer, while examples use ICD-like strings.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Vorn.Tamin.Kiota.Sandbox.Models.DiagnosisID? NoteDetailDrug { get; set; }
#nullable restore
#else
        public global::Vorn.Tamin.Kiota.Sandbox.Models.DiagnosisID NoteDetailDrug { get; set; }
#endif
        /// <summary>The noteDetailsEprscId property</summary>
        public long? NoteDetailsEprscId { get; set; }
        /// <summary>Physiotherapy plan ID; multiple values comma-separated.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PlanId { get; set; }
#nullable restore
#else
        public string PlanId { get; set; }
#endif
        /// <summary>The referenceStatus property</summary>
        public int? ReferenceStatus { get; set; }
        /// <summary>Drug repeat period; repeat count cannot exceed 3 according to notes.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Repeat { get; set; }
#nullable restore
#else
        public string Repeat { get; set; }
#endif
        /// <summary>The srvId property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Vorn.Tamin.Kiota.Sandbox.Models.Service? SrvId { get; set; }
#nullable restore
#else
        public global::Vorn.Tamin.Kiota.Sandbox.Models.Service SrvId { get; set; }
#endif
        /// <summary>The srvQty property</summary>
        public int? SrvQty { get; set; }
        /// <summary>The timesAday property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Vorn.Tamin.Kiota.Sandbox.Models.TbDrugAmount? TimesAday { get; set; }
#nullable restore
#else
        public global::Vorn.Tamin.Kiota.Sandbox.Models.TbDrugAmount TimesAday { get; set; }
#endif
        /// <summary>FDI tooth code when service depends on a tooth.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ToothId { get; set; }
#nullable restore
#else
        public string ToothId { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Vorn.Tamin.Kiota.Sandbox.Models.NoteDetailEprsc"/> and sets the default values.
        /// </summary>
        public NoteDetailEprsc()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Vorn.Tamin.Kiota.Sandbox.Models.NoteDetailEprsc"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Vorn.Tamin.Kiota.Sandbox.Models.NoteDetailEprsc CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Vorn.Tamin.Kiota.Sandbox.Models.NoteDetailEprsc();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "dateDo", n => { DateDo = n.GetStringValue(); } },
                { "dose", n => { Dose = n.GetStringValue(); } },
                { "drugInstruction", n => { DrugInstruction = n.GetObjectValue<global::Vorn.Tamin.Kiota.Sandbox.Models.DrugInstruction>(global::Vorn.Tamin.Kiota.Sandbox.Models.DrugInstruction.CreateFromDiscriminatorValue); } },
                { "illnessId", n => { IllnessId = n.GetStringValue(); } },
                { "isDentalService", n => { IsDentalService = n.GetObjectValue<global::Vorn.Tamin.Kiota.Sandbox.Models.NoteDetailEprsc.NoteDetailEprsc_isDentalService>(global::Vorn.Tamin.Kiota.Sandbox.Models.NoteDetailEprsc.NoteDetailEprsc_isDentalService.CreateFromDiscriminatorValue); } },
                { "noteDetailDrug", n => { NoteDetailDrug = n.GetObjectValue<global::Vorn.Tamin.Kiota.Sandbox.Models.DiagnosisID>(global::Vorn.Tamin.Kiota.Sandbox.Models.DiagnosisID.CreateFromDiscriminatorValue); } },
                { "noteDetailsEprscId", n => { NoteDetailsEprscId = n.GetLongValue(); } },
                { "planId", n => { PlanId = n.GetStringValue(); } },
                { "referenceStatus", n => { ReferenceStatus = n.GetIntValue(); } },
                { "repeat", n => { Repeat = n.GetStringValue(); } },
                { "srvId", n => { SrvId = n.GetObjectValue<global::Vorn.Tamin.Kiota.Sandbox.Models.Service>(global::Vorn.Tamin.Kiota.Sandbox.Models.Service.CreateFromDiscriminatorValue); } },
                { "srvQty", n => { SrvQty = n.GetIntValue(); } },
                { "timesAday", n => { TimesAday = n.GetObjectValue<global::Vorn.Tamin.Kiota.Sandbox.Models.TbDrugAmount>(global::Vorn.Tamin.Kiota.Sandbox.Models.TbDrugAmount.CreateFromDiscriminatorValue); } },
                { "toothId", n => { ToothId = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("dateDo", DateDo);
            writer.WriteStringValue("dose", Dose);
            writer.WriteObjectValue<global::Vorn.Tamin.Kiota.Sandbox.Models.DrugInstruction>("drugInstruction", DrugInstruction);
            writer.WriteStringValue("illnessId", IllnessId);
            writer.WriteObjectValue<global::Vorn.Tamin.Kiota.Sandbox.Models.NoteDetailEprsc.NoteDetailEprsc_isDentalService>("isDentalService", IsDentalService);
            writer.WriteObjectValue<global::Vorn.Tamin.Kiota.Sandbox.Models.DiagnosisID>("noteDetailDrug", NoteDetailDrug);
            writer.WriteLongValue("noteDetailsEprscId", NoteDetailsEprscId);
            writer.WriteStringValue("planId", PlanId);
            writer.WriteIntValue("referenceStatus", ReferenceStatus);
            writer.WriteStringValue("repeat", Repeat);
            writer.WriteObjectValue<global::Vorn.Tamin.Kiota.Sandbox.Models.Service>("srvId", SrvId);
            writer.WriteIntValue("srvQty", SrvQty);
            writer.WriteObjectValue<global::Vorn.Tamin.Kiota.Sandbox.Models.TbDrugAmount>("timesAday", TimesAday);
            writer.WriteStringValue("toothId", ToothId);
            writer.WriteAdditionalData(AdditionalData);
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="int"/>, <see cref="string"/>
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class NoteDetailEprsc_isDentalService : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type <see cref="int"/></summary>
            public int? Integer { get; set; }
            /// <summary>Composed type representation for type <see cref="string"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public string? String { get; set; }
#nullable restore
#else
            public string String { get; set; }
#endif
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::Vorn.Tamin.Kiota.Sandbox.Models.NoteDetailEprsc.NoteDetailEprsc_isDentalService"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::Vorn.Tamin.Kiota.Sandbox.Models.NoteDetailEprsc.NoteDetailEprsc_isDentalService CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
                var mappingValue = parseNode.GetChildNode("")?.GetStringValue();
                var result = new global::Vorn.Tamin.Kiota.Sandbox.Models.NoteDetailEprsc.NoteDetailEprsc_isDentalService();
                if(parseNode.GetIntValue() is int integerValue)
                {
                    result.Integer = integerValue;
                }
                else if(parseNode.GetStringValue() is string stringValue)
                {
                    result.String = stringValue;
                }
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
                if(Integer != null)
                {
                    writer.WriteIntValue(null, Integer);
                }
                else if(String != null)
                {
                    writer.WriteStringValue(null, String);
                }
            }
        }
    }
}
#pragma warning restore CS0618
