// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Vorn.Tamin.Kiota.Sandbox.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class SendEprescRequest : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Required in the test environment; send doctor national code according to PDF.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ClientId { get; set; }
#nullable restore
#else
        public string ClientId { get; set; }
#endif
        /// <summary>The comments property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Comments { get; set; }
#nullable restore
#else
        public string Comments { get; set; }
#endif
        /// <summary>The creatorType property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CreatorType { get; set; }
#nullable restore
#else
        public string CreatorType { get; set; }
#endif
        /// <summary>Medical council number without symbols; midwives use * for Persian letter م.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? DocId { get; set; }
#nullable restore
#else
        public string DocId { get; set; }
#endif
        /// <summary>The docMobileNo property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? DocMobileNo { get; set; }
#nullable restore
#else
        public string DocMobileNo { get; set; }
#endif
        /// <summary>Doctor national code; foreign doctors use FDA-prefixed FIDA code.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? DocNationalCode { get; set; }
#nullable restore
#else
        public string DocNationalCode { get; set; }
#endif
        /// <summary>The expireDate property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ExpireDate { get; set; }
#nullable restore
#else
        public string ExpireDate { get; set; }
#endif
        /// <summary>Patient mobile number; appears in examples and validation notes.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Mobile { get; set; }
#nullable restore
#else
        public string Mobile { get; set; }
#endif
        /// <summary>The noteDetailEprscs property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Vorn.Tamin.Kiota.Sandbox.Models.NoteDetailEprsc>? NoteDetailEprscs { get; set; }
#nullable restore
#else
        public List<global::Vorn.Tamin.Kiota.Sandbox.Models.NoteDetailEprsc> NoteDetailEprscs { get; set; }
#endif
        /// <summary>The noteDetailsReferralList property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Vorn.Tamin.Kiota.Sandbox.Models.NoteDetailsReferral>? NoteDetailsReferralList { get; set; }
#nullable restore
#else
        public List<global::Vorn.Tamin.Kiota.Sandbox.Models.NoteDetailsReferral> NoteDetailsReferralList { get; set; }
#endif
        /// <summary>The noteHeadEprscSupplementary property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Vorn.Tamin.Kiota.Sandbox.Models.Complaint? NoteHeadEprscSupplementary { get; set; }
#nullable restore
#else
        public global::Vorn.Tamin.Kiota.Sandbox.Models.Complaint NoteHeadEprscSupplementary { get; set; }
#endif
        /// <summary>Patient national code.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Patient { get; set; }
#nullable restore
#else
        public string Patient { get; set; }
#endif
        /// <summary>The prescDate property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PrescDate { get; set; }
#nullable restore
#else
        public string PrescDate { get; set; }
#endif
        /// <summary>The prescType property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Vorn.Tamin.Kiota.Sandbox.Models.PrescType? PrescType { get; set; }
#nullable restore
#else
        public global::Vorn.Tamin.Kiota.Sandbox.Models.PrescType PrescType { get; set; }
#endif
        /// <summary>The referralFeedbackId property</summary>
        public long? ReferralFeedbackId { get; set; }
        /// <summary>Required for clinic/hospital/nurse or hospitalization scenarios.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? SiamId { get; set; }
#nullable restore
#else
        public string SiamId { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Vorn.Tamin.Kiota.Sandbox.Models.SendEprescRequest"/> and sets the default values.
        /// </summary>
        public SendEprescRequest()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Vorn.Tamin.Kiota.Sandbox.Models.SendEprescRequest"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Vorn.Tamin.Kiota.Sandbox.Models.SendEprescRequest CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Vorn.Tamin.Kiota.Sandbox.Models.SendEprescRequest();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "clientId", n => { ClientId = n.GetStringValue(); } },
                { "comments", n => { Comments = n.GetStringValue(); } },
                { "creatorType", n => { CreatorType = n.GetStringValue(); } },
                { "docId", n => { DocId = n.GetStringValue(); } },
                { "docMobileNo", n => { DocMobileNo = n.GetStringValue(); } },
                { "docNationalCode", n => { DocNationalCode = n.GetStringValue(); } },
                { "expireDate", n => { ExpireDate = n.GetStringValue(); } },
                { "mobile", n => { Mobile = n.GetStringValue(); } },
                { "noteDetailEprscs", n => { NoteDetailEprscs = n.GetCollectionOfObjectValues<global::Vorn.Tamin.Kiota.Sandbox.Models.NoteDetailEprsc>(global::Vorn.Tamin.Kiota.Sandbox.Models.NoteDetailEprsc.CreateFromDiscriminatorValue)?.AsList(); } },
                { "noteDetailsReferralList", n => { NoteDetailsReferralList = n.GetCollectionOfObjectValues<global::Vorn.Tamin.Kiota.Sandbox.Models.NoteDetailsReferral>(global::Vorn.Tamin.Kiota.Sandbox.Models.NoteDetailsReferral.CreateFromDiscriminatorValue)?.AsList(); } },
                { "noteHeadEprscSupplementary", n => { NoteHeadEprscSupplementary = n.GetObjectValue<global::Vorn.Tamin.Kiota.Sandbox.Models.Complaint>(global::Vorn.Tamin.Kiota.Sandbox.Models.Complaint.CreateFromDiscriminatorValue); } },
                { "patient", n => { Patient = n.GetStringValue(); } },
                { "prescDate", n => { PrescDate = n.GetStringValue(); } },
                { "prescType", n => { PrescType = n.GetObjectValue<global::Vorn.Tamin.Kiota.Sandbox.Models.PrescType>(global::Vorn.Tamin.Kiota.Sandbox.Models.PrescType.CreateFromDiscriminatorValue); } },
                { "referralFeedbackId", n => { ReferralFeedbackId = n.GetLongValue(); } },
                { "siamId", n => { SiamId = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("clientId", ClientId);
            writer.WriteStringValue("comments", Comments);
            writer.WriteStringValue("creatorType", CreatorType);
            writer.WriteStringValue("docId", DocId);
            writer.WriteStringValue("docMobileNo", DocMobileNo);
            writer.WriteStringValue("docNationalCode", DocNationalCode);
            writer.WriteStringValue("expireDate", ExpireDate);
            writer.WriteStringValue("mobile", Mobile);
            writer.WriteCollectionOfObjectValues<global::Vorn.Tamin.Kiota.Sandbox.Models.NoteDetailEprsc>("noteDetailEprscs", NoteDetailEprscs);
            writer.WriteCollectionOfObjectValues<global::Vorn.Tamin.Kiota.Sandbox.Models.NoteDetailsReferral>("noteDetailsReferralList", NoteDetailsReferralList);
            writer.WriteObjectValue<global::Vorn.Tamin.Kiota.Sandbox.Models.Complaint>("noteHeadEprscSupplementary", NoteHeadEprscSupplementary);
            writer.WriteStringValue("patient", Patient);
            writer.WriteStringValue("prescDate", PrescDate);
            writer.WriteObjectValue<global::Vorn.Tamin.Kiota.Sandbox.Models.PrescType>("prescType", PrescType);
            writer.WriteLongValue("referralFeedbackId", ReferralFeedbackId);
            writer.WriteStringValue("siamId", SiamId);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
