// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
using Vorn.Tamin.Kiota.Interface.Epresc.SendEpresc.V2.ReferralList.Item;
namespace Vorn.Tamin.Kiota.Interface.Epresc.SendEpresc.V2.ReferralList
{
    /// <summary>
    /// Builds and executes requests for operations under \interface\epresc\SendEpresc\v2\referralList
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ReferralListRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the Vorn.Tamin.Kiota.interface.epresc.SendEpresc.v2.referralList.item collection</summary>
        /// <param name="position">Registered referral ID</param>
        /// <returns>A <see cref="global::Vorn.Tamin.Kiota.Interface.Epresc.SendEpresc.V2.ReferralList.Item.WithReferralItemRequestBuilder"/></returns>
        public global::Vorn.Tamin.Kiota.Interface.Epresc.SendEpresc.V2.ReferralList.Item.WithReferralItemRequestBuilder this[long position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("referralId", position);
                return new global::Vorn.Tamin.Kiota.Interface.Epresc.SendEpresc.V2.ReferralList.Item.WithReferralItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>Gets an item from the Vorn.Tamin.Kiota.interface.epresc.SendEpresc.v2.referralList.item collection</summary>
        /// <param name="position">Registered referral ID</param>
        /// <returns>A <see cref="global::Vorn.Tamin.Kiota.Interface.Epresc.SendEpresc.V2.ReferralList.Item.WithReferralItemRequestBuilder"/></returns>
        [Obsolete("This indexer is deprecated and will be removed in the next major version. Use the one with the typed parameter instead.")]
        public global::Vorn.Tamin.Kiota.Interface.Epresc.SendEpresc.V2.ReferralList.Item.WithReferralItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                if (!string.IsNullOrWhiteSpace(position)) urlTplParams.Add("referralId", position);
                return new global::Vorn.Tamin.Kiota.Interface.Epresc.SendEpresc.V2.ReferralList.Item.WithReferralItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Vorn.Tamin.Kiota.Interface.Epresc.SendEpresc.V2.ReferralList.ReferralListRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ReferralListRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/interface/epresc/SendEpresc/v2/referralList", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Vorn.Tamin.Kiota.Interface.Epresc.SendEpresc.V2.ReferralList.ReferralListRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ReferralListRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/interface/epresc/SendEpresc/v2/referralList", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
