// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
using Vorn.Tamin.Kiota.Sandbox.Api.V2.Patients.DeserveInfo;
namespace Vorn.Tamin.Kiota.Sandbox.Api.V2.Patients
{
    /// <summary>
    /// Builds and executes requests for operations under \api\v2\patients
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class PatientsRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The deserveInfo property</summary>
        public global::Vorn.Tamin.Kiota.Sandbox.Api.V2.Patients.DeserveInfo.DeserveInfoRequestBuilder DeserveInfo
        {
            get => new global::Vorn.Tamin.Kiota.Sandbox.Api.V2.Patients.DeserveInfo.DeserveInfoRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Vorn.Tamin.Kiota.Sandbox.Api.V2.Patients.PatientsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public PatientsRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/v2/patients", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Vorn.Tamin.Kiota.Sandbox.Api.V2.Patients.PatientsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public PatientsRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/v2/patients", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
