// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
using Vorn.Tamin.Kiota.Interface.Epresc.SendEpresc.V2.FindDentistServiceNameWithoutTooth.Item;
namespace Vorn.Tamin.Kiota.Interface.Epresc.SendEpresc.V2.FindDentistServiceNameWithoutTooth
{
    /// <summary>
    /// Builds and executes requests for operations under \interface\epresc\SendEpresc\v2\find-dentist-service-name-without-tooth
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class FindDentistServiceNameWithoutToothRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the Vorn.Tamin.Kiota.interface.epresc.SendEpresc.v2.findDentistServiceNameWithoutTooth.item collection</summary>
        /// <param name="position">Dental service type; 1 for health care services, 2 for dental services</param>
        /// <returns>A <see cref="global::Vorn.Tamin.Kiota.Interface.Epresc.SendEpresc.V2.FindDentistServiceNameWithoutTooth.Item.WithDentistTypeItemRequestBuilder"/></returns>
        public global::Vorn.Tamin.Kiota.Interface.Epresc.SendEpresc.V2.FindDentistServiceNameWithoutTooth.Item.WithDentistTypeItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("dentistType", position);
                return new global::Vorn.Tamin.Kiota.Interface.Epresc.SendEpresc.V2.FindDentistServiceNameWithoutTooth.Item.WithDentistTypeItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Vorn.Tamin.Kiota.Interface.Epresc.SendEpresc.V2.FindDentistServiceNameWithoutTooth.FindDentistServiceNameWithoutToothRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public FindDentistServiceNameWithoutToothRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/interface/epresc/SendEpresc/v2/find-dentist-service-name-without-tooth", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Vorn.Tamin.Kiota.Interface.Epresc.SendEpresc.V2.FindDentistServiceNameWithoutTooth.FindDentistServiceNameWithoutToothRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public FindDentistServiceNameWithoutToothRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/interface/epresc/SendEpresc/v2/find-dentist-service-name-without-tooth", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
