// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
using Vorn.Tamin.Kiota.Sandbox.Api.V2.Ep.FindNoteReferral.Item.Item;
namespace Vorn.Tamin.Kiota.Sandbox.Api.V2.Ep.FindNoteReferral.Item
{
    /// <summary>
    /// Builds and executes requests for operations under \api\v2\ep\findNoteReferral\{master-id}
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class MasterItemRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the Vorn.Tamin.Kiota.Sandbox.api.v2.ep.findNoteReferral.item.item collection</summary>
        /// <param name="position">Patient national code</param>
        /// <returns>A <see cref="global::Vorn.Tamin.Kiota.Sandbox.Api.V2.Ep.FindNoteReferral.Item.Item.DocItemRequestBuilder"/></returns>
        public global::Vorn.Tamin.Kiota.Sandbox.Api.V2.Ep.FindNoteReferral.Item.Item.DocItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("doc%2Did", position);
                return new global::Vorn.Tamin.Kiota.Sandbox.Api.V2.Ep.FindNoteReferral.Item.Item.DocItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Vorn.Tamin.Kiota.Sandbox.Api.V2.Ep.FindNoteReferral.Item.MasterItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public MasterItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/v2/ep/findNoteReferral/{master%2Did}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Vorn.Tamin.Kiota.Sandbox.Api.V2.Ep.FindNoteReferral.Item.MasterItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public MasterItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/v2/ep/findNoteReferral/{master%2Did}", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
