// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
using Vorn.Tamin.Kiota.Sandbox.Api.V2.Patients.DeserveInfo.Item;
namespace Vorn.Tamin.Kiota.Sandbox.Api.V2.Patients.DeserveInfo
{
    /// <summary>
    /// Builds and executes requests for operations under \api\v2\patients\deserve-info
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class DeserveInfoRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the Vorn.Tamin.Kiota.Sandbox.api.v2.patients.deserveInfo.item collection</summary>
        /// <param name="position">Path parameter from test endpoint template: requestBy</param>
        /// <returns>A <see cref="global::Vorn.Tamin.Kiota.Sandbox.Api.V2.Patients.DeserveInfo.Item.WithRequestByItemRequestBuilder"/></returns>
        public global::Vorn.Tamin.Kiota.Sandbox.Api.V2.Patients.DeserveInfo.Item.WithRequestByItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("requestBy", position);
                return new global::Vorn.Tamin.Kiota.Sandbox.Api.V2.Patients.DeserveInfo.Item.WithRequestByItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Vorn.Tamin.Kiota.Sandbox.Api.V2.Patients.DeserveInfo.DeserveInfoRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public DeserveInfoRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/v2/patients/deserve-info", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Vorn.Tamin.Kiota.Sandbox.Api.V2.Patients.DeserveInfo.DeserveInfoRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public DeserveInfoRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/v2/patients/deserve-info", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
