// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
using Vorn.Tamin.Kiota.Interface.Epresc.SendEpresc.V2.Referral.NoteDetail;
namespace Vorn.Tamin.Kiota.Interface.Epresc.SendEpresc.V2.Referral
{
    /// <summary>
    /// Builds and executes requests for operations under \interface\epresc\SendEpresc\v2\referral
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ReferralRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The noteDetail property</summary>
        public global::Vorn.Tamin.Kiota.Interface.Epresc.SendEpresc.V2.Referral.NoteDetail.NoteDetailRequestBuilder NoteDetail
        {
            get => new global::Vorn.Tamin.Kiota.Interface.Epresc.SendEpresc.V2.Referral.NoteDetail.NoteDetailRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Vorn.Tamin.Kiota.Interface.Epresc.SendEpresc.V2.Referral.ReferralRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ReferralRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/interface/epresc/SendEpresc/v2/referral", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Vorn.Tamin.Kiota.Interface.Epresc.SendEpresc.V2.Referral.ReferralRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ReferralRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/interface/epresc/SendEpresc/v2/referral", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
