// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
using Vorn.Tamin.Kiota.Sandbox.Api.CartablenoteDetailsReferral.Item;
namespace Vorn.Tamin.Kiota.Sandbox.Api.CartablenoteDetailsReferral
{
    /// <summary>
    /// Builds and executes requests for operations under \api\cartablenoteDetailsReferral
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class CartablenoteDetailsReferralRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the Vorn.Tamin.Kiota.Sandbox.api.cartablenoteDetailsReferral.item collection</summary>
        /// <param name="position">Doctor national code</param>
        /// <returns>A <see cref="global::Vorn.Tamin.Kiota.Sandbox.Api.CartablenoteDetailsReferral.Item.WithDocNationalCodeItemRequestBuilder"/></returns>
        public global::Vorn.Tamin.Kiota.Sandbox.Api.CartablenoteDetailsReferral.Item.WithDocNationalCodeItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("docNationalCode", position);
                return new global::Vorn.Tamin.Kiota.Sandbox.Api.CartablenoteDetailsReferral.Item.WithDocNationalCodeItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Vorn.Tamin.Kiota.Sandbox.Api.CartablenoteDetailsReferral.CartablenoteDetailsReferralRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public CartablenoteDetailsReferralRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/cartablenoteDetailsReferral", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Vorn.Tamin.Kiota.Sandbox.Api.CartablenoteDetailsReferral.CartablenoteDetailsReferralRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public CartablenoteDetailsReferralRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/cartablenoteDetailsReferral", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
