// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
using Vorn.Tamin.Kiota.Interface.Epresc.SendEpresc.V2.CartableNurse;
using Vorn.Tamin.Kiota.Interface.Epresc.SendEpresc.V2.CheckRulesInDetail;
using Vorn.Tamin.Kiota.Interface.Epresc.SendEpresc.V2.Complaint;
using Vorn.Tamin.Kiota.Interface.Epresc.SendEpresc.V2.DrugAmount;
using Vorn.Tamin.Kiota.Interface.Epresc.SendEpresc.V2.DrugInstruction;
using Vorn.Tamin.Kiota.Interface.Epresc.SendEpresc.V2.DrugUsage;
using Vorn.Tamin.Kiota.Interface.Epresc.SendEpresc.V2.Edit;
using Vorn.Tamin.Kiota.Interface.Epresc.SendEpresc.V2.FetchReferralCartable;
using Vorn.Tamin.Kiota.Interface.Epresc.SendEpresc.V2.FindDentistServiceNameByTooth;
using Vorn.Tamin.Kiota.Interface.Epresc.SendEpresc.V2.FindDentistServiceNameWithoutTooth;
using Vorn.Tamin.Kiota.Interface.Epresc.SendEpresc.V2.FindNoteReferral;
using Vorn.Tamin.Kiota.Interface.Epresc.SendEpresc.V2.HospitalizationOrder;
using Vorn.Tamin.Kiota.Interface.Epresc.SendEpresc.V2.Icd10;
using Vorn.Tamin.Kiota.Interface.Epresc.SendEpresc.V2.Item;
using Vorn.Tamin.Kiota.Interface.Epresc.SendEpresc.V2.NoteDetailsReferral;
using Vorn.Tamin.Kiota.Interface.Epresc.SendEpresc.V2.ParTaref;
using Vorn.Tamin.Kiota.Interface.Epresc.SendEpresc.V2.PatientNoteDetailsReferral;
using Vorn.Tamin.Kiota.Interface.Epresc.SendEpresc.V2.PhIllness;
using Vorn.Tamin.Kiota.Interface.Epresc.SendEpresc.V2.PhPlan;
using Vorn.Tamin.Kiota.Interface.Epresc.SendEpresc.V2.PrescriptionType;
using Vorn.Tamin.Kiota.Interface.Epresc.SendEpresc.V2.Referral;
using Vorn.Tamin.Kiota.Interface.Epresc.SendEpresc.V2.ReferralList;
using Vorn.Tamin.Kiota.Interface.Epresc.SendEpresc.V2.Remove;
using Vorn.Tamin.Kiota.Interface.Epresc.SendEpresc.V2.ServiceType;
using Vorn.Tamin.Kiota.Interface.Epresc.SendEpresc.V2.Services;
using Vorn.Tamin.Kiota.Interface.Epresc.SendEpresc.V2.Special;
using Vorn.Tamin.Kiota.Models;
namespace Vorn.Tamin.Kiota.Interface.Epresc.SendEpresc.V2
{
    /// <summary>
    /// Builds and executes requests for operations under \interface\epresc\SendEpresc\v2
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class V2RequestBuilder : BaseRequestBuilder
    {
        /// <summary>The cartableNurse property</summary>
        public global::Vorn.Tamin.Kiota.Interface.Epresc.SendEpresc.V2.CartableNurse.CartableNurseRequestBuilder CartableNurse
        {
            get => new global::Vorn.Tamin.Kiota.Interface.Epresc.SendEpresc.V2.CartableNurse.CartableNurseRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The checkRulesInDetail property</summary>
        public global::Vorn.Tamin.Kiota.Interface.Epresc.SendEpresc.V2.CheckRulesInDetail.CheckRulesInDetailRequestBuilder CheckRulesInDetail
        {
            get => new global::Vorn.Tamin.Kiota.Interface.Epresc.SendEpresc.V2.CheckRulesInDetail.CheckRulesInDetailRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The complaint property</summary>
        public global::Vorn.Tamin.Kiota.Interface.Epresc.SendEpresc.V2.Complaint.ComplaintRequestBuilder Complaint
        {
            get => new global::Vorn.Tamin.Kiota.Interface.Epresc.SendEpresc.V2.Complaint.ComplaintRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The drugAmount property</summary>
        public global::Vorn.Tamin.Kiota.Interface.Epresc.SendEpresc.V2.DrugAmount.DrugAmountRequestBuilder DrugAmount
        {
            get => new global::Vorn.Tamin.Kiota.Interface.Epresc.SendEpresc.V2.DrugAmount.DrugAmountRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The drugInstruction property</summary>
        public global::Vorn.Tamin.Kiota.Interface.Epresc.SendEpresc.V2.DrugInstruction.DrugInstructionRequestBuilder DrugInstruction
        {
            get => new global::Vorn.Tamin.Kiota.Interface.Epresc.SendEpresc.V2.DrugInstruction.DrugInstructionRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The drugUsage property</summary>
        public global::Vorn.Tamin.Kiota.Interface.Epresc.SendEpresc.V2.DrugUsage.DrugUsageRequestBuilder DrugUsage
        {
            get => new global::Vorn.Tamin.Kiota.Interface.Epresc.SendEpresc.V2.DrugUsage.DrugUsageRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The edit property</summary>
        public global::Vorn.Tamin.Kiota.Interface.Epresc.SendEpresc.V2.Edit.EditRequestBuilder Edit
        {
            get => new global::Vorn.Tamin.Kiota.Interface.Epresc.SendEpresc.V2.Edit.EditRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The fetchReferralCartable property</summary>
        public global::Vorn.Tamin.Kiota.Interface.Epresc.SendEpresc.V2.FetchReferralCartable.FetchReferralCartableRequestBuilder FetchReferralCartable
        {
            get => new global::Vorn.Tamin.Kiota.Interface.Epresc.SendEpresc.V2.FetchReferralCartable.FetchReferralCartableRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The findDentistServiceNameByTooth property</summary>
        public global::Vorn.Tamin.Kiota.Interface.Epresc.SendEpresc.V2.FindDentistServiceNameByTooth.FindDentistServiceNameByToothRequestBuilder FindDentistServiceNameByTooth
        {
            get => new global::Vorn.Tamin.Kiota.Interface.Epresc.SendEpresc.V2.FindDentistServiceNameByTooth.FindDentistServiceNameByToothRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The findDentistServiceNameWithoutTooth property</summary>
        public global::Vorn.Tamin.Kiota.Interface.Epresc.SendEpresc.V2.FindDentistServiceNameWithoutTooth.FindDentistServiceNameWithoutToothRequestBuilder FindDentistServiceNameWithoutTooth
        {
            get => new global::Vorn.Tamin.Kiota.Interface.Epresc.SendEpresc.V2.FindDentistServiceNameWithoutTooth.FindDentistServiceNameWithoutToothRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The findNoteReferral property</summary>
        public global::Vorn.Tamin.Kiota.Interface.Epresc.SendEpresc.V2.FindNoteReferral.FindNoteReferralRequestBuilder FindNoteReferral
        {
            get => new global::Vorn.Tamin.Kiota.Interface.Epresc.SendEpresc.V2.FindNoteReferral.FindNoteReferralRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The hospitalizationOrder property</summary>
        public global::Vorn.Tamin.Kiota.Interface.Epresc.SendEpresc.V2.HospitalizationOrder.HospitalizationOrderRequestBuilder HospitalizationOrder
        {
            get => new global::Vorn.Tamin.Kiota.Interface.Epresc.SendEpresc.V2.HospitalizationOrder.HospitalizationOrderRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The icd10 property</summary>
        public global::Vorn.Tamin.Kiota.Interface.Epresc.SendEpresc.V2.Icd10.Icd10RequestBuilder Icd10
        {
            get => new global::Vorn.Tamin.Kiota.Interface.Epresc.SendEpresc.V2.Icd10.Icd10RequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The noteDetailsReferral property</summary>
        public global::Vorn.Tamin.Kiota.Interface.Epresc.SendEpresc.V2.NoteDetailsReferral.NoteDetailsReferralRequestBuilder NoteDetailsReferral
        {
            get => new global::Vorn.Tamin.Kiota.Interface.Epresc.SendEpresc.V2.NoteDetailsReferral.NoteDetailsReferralRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The parTaref property</summary>
        public global::Vorn.Tamin.Kiota.Interface.Epresc.SendEpresc.V2.ParTaref.ParTarefRequestBuilder ParTaref
        {
            get => new global::Vorn.Tamin.Kiota.Interface.Epresc.SendEpresc.V2.ParTaref.ParTarefRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The patientNoteDetailsReferral property</summary>
        public global::Vorn.Tamin.Kiota.Interface.Epresc.SendEpresc.V2.PatientNoteDetailsReferral.PatientNoteDetailsReferralRequestBuilder PatientNoteDetailsReferral
        {
            get => new global::Vorn.Tamin.Kiota.Interface.Epresc.SendEpresc.V2.PatientNoteDetailsReferral.PatientNoteDetailsReferralRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The phIllness property</summary>
        public global::Vorn.Tamin.Kiota.Interface.Epresc.SendEpresc.V2.PhIllness.PhIllnessRequestBuilder PhIllness
        {
            get => new global::Vorn.Tamin.Kiota.Interface.Epresc.SendEpresc.V2.PhIllness.PhIllnessRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The phPlan property</summary>
        public global::Vorn.Tamin.Kiota.Interface.Epresc.SendEpresc.V2.PhPlan.PhPlanRequestBuilder PhPlan
        {
            get => new global::Vorn.Tamin.Kiota.Interface.Epresc.SendEpresc.V2.PhPlan.PhPlanRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The prescriptionType property</summary>
        public global::Vorn.Tamin.Kiota.Interface.Epresc.SendEpresc.V2.PrescriptionType.PrescriptionTypeRequestBuilder PrescriptionType
        {
            get => new global::Vorn.Tamin.Kiota.Interface.Epresc.SendEpresc.V2.PrescriptionType.PrescriptionTypeRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The referral property</summary>
        public global::Vorn.Tamin.Kiota.Interface.Epresc.SendEpresc.V2.Referral.ReferralRequestBuilder Referral
        {
            get => new global::Vorn.Tamin.Kiota.Interface.Epresc.SendEpresc.V2.Referral.ReferralRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The referralList property</summary>
        public global::Vorn.Tamin.Kiota.Interface.Epresc.SendEpresc.V2.ReferralList.ReferralListRequestBuilder ReferralList
        {
            get => new global::Vorn.Tamin.Kiota.Interface.Epresc.SendEpresc.V2.ReferralList.ReferralListRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The remove property</summary>
        public global::Vorn.Tamin.Kiota.Interface.Epresc.SendEpresc.V2.Remove.RemoveRequestBuilder Remove
        {
            get => new global::Vorn.Tamin.Kiota.Interface.Epresc.SendEpresc.V2.Remove.RemoveRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The services property</summary>
        public global::Vorn.Tamin.Kiota.Interface.Epresc.SendEpresc.V2.Services.ServicesRequestBuilder Services
        {
            get => new global::Vorn.Tamin.Kiota.Interface.Epresc.SendEpresc.V2.Services.ServicesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The serviceType property</summary>
        public global::Vorn.Tamin.Kiota.Interface.Epresc.SendEpresc.V2.ServiceType.ServiceTypeRequestBuilder ServiceType
        {
            get => new global::Vorn.Tamin.Kiota.Interface.Epresc.SendEpresc.V2.ServiceType.ServiceTypeRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The special property</summary>
        public global::Vorn.Tamin.Kiota.Interface.Epresc.SendEpresc.V2.Special.SpecialRequestBuilder Special
        {
            get => new global::Vorn.Tamin.Kiota.Interface.Epresc.SendEpresc.V2.Special.SpecialRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>Gets an item from the Vorn.Tamin.Kiota.interface.epresc.SendEpresc.v2.item collection</summary>
        /// <param name="position">Unique prescription header ID</param>
        /// <returns>A <see cref="global::Vorn.Tamin.Kiota.Interface.Epresc.SendEpresc.V2.Item.HeaderItemRequestBuilder"/></returns>
        public global::Vorn.Tamin.Kiota.Interface.Epresc.SendEpresc.V2.Item.HeaderItemRequestBuilder this[int position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("header%2Did", position);
                return new global::Vorn.Tamin.Kiota.Interface.Epresc.SendEpresc.V2.Item.HeaderItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>Gets an item from the Vorn.Tamin.Kiota.interface.epresc.SendEpresc.v2.item collection</summary>
        /// <param name="position">Unique prescription header ID</param>
        /// <returns>A <see cref="global::Vorn.Tamin.Kiota.Interface.Epresc.SendEpresc.V2.Item.HeaderItemRequestBuilder"/></returns>
        [Obsolete("This indexer is deprecated and will be removed in the next major version. Use the one with the typed parameter instead.")]
        public global::Vorn.Tamin.Kiota.Interface.Epresc.SendEpresc.V2.Item.HeaderItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                if (!string.IsNullOrWhiteSpace(position)) urlTplParams.Add("header%2Did", position);
                return new global::Vorn.Tamin.Kiota.Interface.Epresc.SendEpresc.V2.Item.HeaderItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Vorn.Tamin.Kiota.Interface.Epresc.SendEpresc.V2.V2RequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public V2RequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/interface/epresc/SendEpresc/v2", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Vorn.Tamin.Kiota.Interface.Epresc.SendEpresc.V2.V2RequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public V2RequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/interface/epresc/SendEpresc/v2", rawUrl)
        {
        }
        /// <summary>
        /// Register electronic prescription
        /// </summary>
        /// <returns>A <see cref="global::Vorn.Tamin.Kiota.Models.SendEprescResponse"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Vorn.Tamin.Kiota.Models.ErrorResponse">When receiving a 400 status code</exception>
        /// <exception cref="global::Vorn.Tamin.Kiota.Models.ErrorResponse">When receiving a 401 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Vorn.Tamin.Kiota.Models.SendEprescResponse?> PostAsync(global::Vorn.Tamin.Kiota.Models.SendEprescRequest body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Vorn.Tamin.Kiota.Models.SendEprescResponse> PostAsync(global::Vorn.Tamin.Kiota.Models.SendEprescRequest body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPostRequestInformation(body, requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::Vorn.Tamin.Kiota.Models.ErrorResponse.CreateFromDiscriminatorValue },
                { "401", global::Vorn.Tamin.Kiota.Models.ErrorResponse.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Vorn.Tamin.Kiota.Models.SendEprescResponse>(requestInfo, global::Vorn.Tamin.Kiota.Models.SendEprescResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Register electronic prescription
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPostRequestInformation(global::Vorn.Tamin.Kiota.Models.SendEprescRequest body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPostRequestInformation(global::Vorn.Tamin.Kiota.Models.SendEprescRequest body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = new RequestInformation(Method.POST, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            requestInfo.SetContentFromParsable(RequestAdapter, "application/json", body);
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Vorn.Tamin.Kiota.Interface.Epresc.SendEpresc.V2.V2RequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Vorn.Tamin.Kiota.Interface.Epresc.SendEpresc.V2.V2RequestBuilder WithUrl(string rawUrl)
        {
            return new global::Vorn.Tamin.Kiota.Interface.Epresc.SendEpresc.V2.V2RequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class V2RequestBuilderPostRequestConfiguration : RequestConfiguration<DefaultQueryParameters>
        {
        }
    }
}
#pragma warning restore CS0618
