// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
using Vorn.Tamin.Kiota.Auth.Server.Authorize;
using Vorn.Tamin.Kiota.Auth.Server.Token;
using Vorn.Tamin.Kiota.Auth.Server.V2;
namespace Vorn.Tamin.Kiota.Auth.Server
{
    /// <summary>
    /// Builds and executes requests for operations under \auth\server
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ServerRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The authorize property</summary>
        public global::Vorn.Tamin.Kiota.Auth.Server.Authorize.AuthorizeRequestBuilder Authorize
        {
            get => new global::Vorn.Tamin.Kiota.Auth.Server.Authorize.AuthorizeRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The token property</summary>
        public global::Vorn.Tamin.Kiota.Auth.Server.Token.TokenRequestBuilder Token
        {
            get => new global::Vorn.Tamin.Kiota.Auth.Server.Token.TokenRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The v2 property</summary>
        public global::Vorn.Tamin.Kiota.Auth.Server.V2.V2RequestBuilder V2
        {
            get => new global::Vorn.Tamin.Kiota.Auth.Server.V2.V2RequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Vorn.Tamin.Kiota.Auth.Server.ServerRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ServerRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/auth/server", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Vorn.Tamin.Kiota.Auth.Server.ServerRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ServerRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/auth/server", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
