// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
using Vorn.Tamin.Kiota.Sandbox.Api.V2.Ep.FindNoteReferral;
using Vorn.Tamin.Kiota.Sandbox.Api.V2.Ep.Item;
using Vorn.Tamin.Kiota.Sandbox.Api.V2.Ep.Update;
namespace Vorn.Tamin.Kiota.Sandbox.Api.V2.Ep
{
    /// <summary>
    /// Builds and executes requests for operations under \api\v2\ep
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class EpRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The findNoteReferral property</summary>
        public global::Vorn.Tamin.Kiota.Sandbox.Api.V2.Ep.FindNoteReferral.FindNoteReferralRequestBuilder FindNoteReferral
        {
            get => new global::Vorn.Tamin.Kiota.Sandbox.Api.V2.Ep.FindNoteReferral.FindNoteReferralRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The update property</summary>
        public global::Vorn.Tamin.Kiota.Sandbox.Api.V2.Ep.Update.UpdateRequestBuilder Update
        {
            get => new global::Vorn.Tamin.Kiota.Sandbox.Api.V2.Ep.Update.UpdateRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>Gets an item from the Vorn.Tamin.Kiota.Sandbox.api.v2.ep.item collection</summary>
        /// <param name="position">Unique prescription header ID</param>
        /// <returns>A <see cref="global::Vorn.Tamin.Kiota.Sandbox.Api.V2.Ep.Item.HeaderItemRequestBuilder"/></returns>
        public global::Vorn.Tamin.Kiota.Sandbox.Api.V2.Ep.Item.HeaderItemRequestBuilder this[int position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("header%2Did", position);
                return new global::Vorn.Tamin.Kiota.Sandbox.Api.V2.Ep.Item.HeaderItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>Gets an item from the Vorn.Tamin.Kiota.Sandbox.api.v2.ep.item collection</summary>
        /// <param name="position">Unique prescription header ID</param>
        /// <returns>A <see cref="global::Vorn.Tamin.Kiota.Sandbox.Api.V2.Ep.Item.HeaderItemRequestBuilder"/></returns>
        [Obsolete("This indexer is deprecated and will be removed in the next major version. Use the one with the typed parameter instead.")]
        public global::Vorn.Tamin.Kiota.Sandbox.Api.V2.Ep.Item.HeaderItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                if (!string.IsNullOrWhiteSpace(position)) urlTplParams.Add("header%2Did", position);
                return new global::Vorn.Tamin.Kiota.Sandbox.Api.V2.Ep.Item.HeaderItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Vorn.Tamin.Kiota.Sandbox.Api.V2.Ep.EpRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public EpRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/v2/ep", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Vorn.Tamin.Kiota.Sandbox.Api.V2.Ep.EpRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public EpRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/v2/ep", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
