// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
using Vorn.Tamin.Kiota.Interface.Epresc.SendEpresc.V2.NoteDetailsReferral.Count.Item;
namespace Vorn.Tamin.Kiota.Interface.Epresc.SendEpresc.V2.NoteDetailsReferral.Count
{
    /// <summary>
    /// Builds and executes requests for operations under \interface\epresc\SendEpresc\v2\noteDetailsReferral\count
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class CountRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the Vorn.Tamin.Kiota.interface.epresc.SendEpresc.v2.noteDetailsReferral.count.item collection</summary>
        /// <param name="position">Patient national code</param>
        /// <returns>A <see cref="global::Vorn.Tamin.Kiota.Interface.Epresc.SendEpresc.V2.NoteDetailsReferral.Count.Item.WithNationalCodeItemRequestBuilder"/></returns>
        public global::Vorn.Tamin.Kiota.Interface.Epresc.SendEpresc.V2.NoteDetailsReferral.Count.Item.WithNationalCodeItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("nationalCode", position);
                return new global::Vorn.Tamin.Kiota.Interface.Epresc.SendEpresc.V2.NoteDetailsReferral.Count.Item.WithNationalCodeItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Vorn.Tamin.Kiota.Interface.Epresc.SendEpresc.V2.NoteDetailsReferral.Count.CountRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public CountRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/interface/epresc/SendEpresc/v2/noteDetailsReferral/count", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Vorn.Tamin.Kiota.Interface.Epresc.SendEpresc.V2.NoteDetailsReferral.Count.CountRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public CountRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/interface/epresc/SendEpresc/v2/noteDetailsReferral/count", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
