// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
using Vorn.Tamin.Kiota.Sandbox.Api.V2.CartableNurse;
using Vorn.Tamin.Kiota.Sandbox.Api.V2.CheckRulesInDetail;
using Vorn.Tamin.Kiota.Sandbox.Api.V2.Ep;
using Vorn.Tamin.Kiota.Sandbox.Api.V2.NoteDetailsReferral;
using Vorn.Tamin.Kiota.Sandbox.Api.V2.Patients;
using Vorn.Tamin.Kiota.Sandbox.Api.V2.Referral;
using Vorn.Tamin.Kiota.Sandbox.Api.V2.SendEpresc;
using Vorn.Tamin.Kiota.Sandbox.Api.V2.WsDentistBase;
using Vorn.Tamin.Kiota.Sandbox.Api.V2.WsDrugAmoun;
using Vorn.Tamin.Kiota.Sandbox.Api.V2.WsDrugInstruction;
using Vorn.Tamin.Kiota.Sandbox.Api.V2.WsDrugUsage;
using Vorn.Tamin.Kiota.Sandbox.Api.V2.WsParTaref;
using Vorn.Tamin.Kiota.Sandbox.Api.V2.WsPhIllness;
using Vorn.Tamin.Kiota.Sandbox.Api.V2.WsPhPlan;
using Vorn.Tamin.Kiota.Sandbox.Api.V2.WsPrescriptionType;
using Vorn.Tamin.Kiota.Sandbox.Api.V2.WsServiceType;
using Vorn.Tamin.Kiota.Sandbox.Api.V2.WsServices;
namespace Vorn.Tamin.Kiota.Sandbox.Api.V2
{
    /// <summary>
    /// Builds and executes requests for operations under \api\v2
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class V2RequestBuilder : BaseRequestBuilder
    {
        /// <summary>The cartableNurse property</summary>
        public global::Vorn.Tamin.Kiota.Sandbox.Api.V2.CartableNurse.CartableNurseRequestBuilder CartableNurse
        {
            get => new global::Vorn.Tamin.Kiota.Sandbox.Api.V2.CartableNurse.CartableNurseRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The checkRulesInDetail property</summary>
        public global::Vorn.Tamin.Kiota.Sandbox.Api.V2.CheckRulesInDetail.CheckRulesInDetailRequestBuilder CheckRulesInDetail
        {
            get => new global::Vorn.Tamin.Kiota.Sandbox.Api.V2.CheckRulesInDetail.CheckRulesInDetailRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The ep property</summary>
        public global::Vorn.Tamin.Kiota.Sandbox.Api.V2.Ep.EpRequestBuilder Ep
        {
            get => new global::Vorn.Tamin.Kiota.Sandbox.Api.V2.Ep.EpRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The noteDetailsReferral property</summary>
        public global::Vorn.Tamin.Kiota.Sandbox.Api.V2.NoteDetailsReferral.NoteDetailsReferralRequestBuilder NoteDetailsReferral
        {
            get => new global::Vorn.Tamin.Kiota.Sandbox.Api.V2.NoteDetailsReferral.NoteDetailsReferralRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The patients property</summary>
        public global::Vorn.Tamin.Kiota.Sandbox.Api.V2.Patients.PatientsRequestBuilder Patients
        {
            get => new global::Vorn.Tamin.Kiota.Sandbox.Api.V2.Patients.PatientsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The referral property</summary>
        public global::Vorn.Tamin.Kiota.Sandbox.Api.V2.Referral.ReferralRequestBuilder Referral
        {
            get => new global::Vorn.Tamin.Kiota.Sandbox.Api.V2.Referral.ReferralRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The SendEpresc property</summary>
        public global::Vorn.Tamin.Kiota.Sandbox.Api.V2.SendEpresc.SendEprescRequestBuilder SendEpresc
        {
            get => new global::Vorn.Tamin.Kiota.Sandbox.Api.V2.SendEpresc.SendEprescRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The wsDentistBase property</summary>
        public global::Vorn.Tamin.Kiota.Sandbox.Api.V2.WsDentistBase.WsDentistBaseRequestBuilder WsDentistBase
        {
            get => new global::Vorn.Tamin.Kiota.Sandbox.Api.V2.WsDentistBase.WsDentistBaseRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The wsDrugAmoun property</summary>
        public global::Vorn.Tamin.Kiota.Sandbox.Api.V2.WsDrugAmoun.WsDrugAmounRequestBuilder WsDrugAmoun
        {
            get => new global::Vorn.Tamin.Kiota.Sandbox.Api.V2.WsDrugAmoun.WsDrugAmounRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The wsDrugInstruction property</summary>
        public global::Vorn.Tamin.Kiota.Sandbox.Api.V2.WsDrugInstruction.WsDrugInstructionRequestBuilder WsDrugInstruction
        {
            get => new global::Vorn.Tamin.Kiota.Sandbox.Api.V2.WsDrugInstruction.WsDrugInstructionRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The wsDrugUsage property</summary>
        public global::Vorn.Tamin.Kiota.Sandbox.Api.V2.WsDrugUsage.WsDrugUsageRequestBuilder WsDrugUsage
        {
            get => new global::Vorn.Tamin.Kiota.Sandbox.Api.V2.WsDrugUsage.WsDrugUsageRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The wsParTaref property</summary>
        public global::Vorn.Tamin.Kiota.Sandbox.Api.V2.WsParTaref.WsParTarefRequestBuilder WsParTaref
        {
            get => new global::Vorn.Tamin.Kiota.Sandbox.Api.V2.WsParTaref.WsParTarefRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The wsPhIllness property</summary>
        public global::Vorn.Tamin.Kiota.Sandbox.Api.V2.WsPhIllness.WsPhIllnessRequestBuilder WsPhIllness
        {
            get => new global::Vorn.Tamin.Kiota.Sandbox.Api.V2.WsPhIllness.WsPhIllnessRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The wsPhPlan property</summary>
        public global::Vorn.Tamin.Kiota.Sandbox.Api.V2.WsPhPlan.WsPhPlanRequestBuilder WsPhPlan
        {
            get => new global::Vorn.Tamin.Kiota.Sandbox.Api.V2.WsPhPlan.WsPhPlanRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The wsPrescriptionType property</summary>
        public global::Vorn.Tamin.Kiota.Sandbox.Api.V2.WsPrescriptionType.WsPrescriptionTypeRequestBuilder WsPrescriptionType
        {
            get => new global::Vorn.Tamin.Kiota.Sandbox.Api.V2.WsPrescriptionType.WsPrescriptionTypeRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The wsServices property</summary>
        public global::Vorn.Tamin.Kiota.Sandbox.Api.V2.WsServices.WsServicesRequestBuilder WsServices
        {
            get => new global::Vorn.Tamin.Kiota.Sandbox.Api.V2.WsServices.WsServicesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The wsServiceType property</summary>
        public global::Vorn.Tamin.Kiota.Sandbox.Api.V2.WsServiceType.WsServiceTypeRequestBuilder WsServiceType
        {
            get => new global::Vorn.Tamin.Kiota.Sandbox.Api.V2.WsServiceType.WsServiceTypeRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Vorn.Tamin.Kiota.Sandbox.Api.V2.V2RequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public V2RequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/v2", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Vorn.Tamin.Kiota.Sandbox.Api.V2.V2RequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public V2RequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/v2", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
