// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
using Vorn.Tamin.Kiota.Interface.Epresc.SendEpresc.V2.Icd10.GetAll;
namespace Vorn.Tamin.Kiota.Interface.Epresc.SendEpresc.V2.Icd10
{
    /// <summary>
    /// Builds and executes requests for operations under \interface\epresc\SendEpresc\v2\icd10
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class Icd10RequestBuilder : BaseRequestBuilder
    {
        /// <summary>The getAll property</summary>
        public global::Vorn.Tamin.Kiota.Interface.Epresc.SendEpresc.V2.Icd10.GetAll.GetAllRequestBuilder GetAll
        {
            get => new global::Vorn.Tamin.Kiota.Interface.Epresc.SendEpresc.V2.Icd10.GetAll.GetAllRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Vorn.Tamin.Kiota.Interface.Epresc.SendEpresc.V2.Icd10.Icd10RequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public Icd10RequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/interface/epresc/SendEpresc/v2/icd10", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Vorn.Tamin.Kiota.Interface.Epresc.SendEpresc.V2.Icd10.Icd10RequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public Icd10RequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/interface/epresc/SendEpresc/v2/icd10", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
