// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Vorn.Tamin.Kiota.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class Service : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The parTarefGrp property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Vorn.Tamin.Kiota.Models.ParTarefGroup? ParTarefGrp { get; set; }
#nullable restore
#else
        public global::Vorn.Tamin.Kiota.Models.ParTarefGroup ParTarefGrp { get; set; }
#endif
        /// <summary>The srvCode property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? SrvCode { get; set; }
#nullable restore
#else
        public string SrvCode { get; set; }
#endif
        /// <summary>The srvCodeComplete property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? SrvCodeComplete { get; set; }
#nullable restore
#else
        public string SrvCodeComplete { get; set; }
#endif
        /// <summary>The srvId property</summary>
        public int? SrvId { get; set; }
        /// <summary>The srvName property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? SrvName { get; set; }
#nullable restore
#else
        public string SrvName { get; set; }
#endif
        /// <summary>The srvType property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Vorn.Tamin.Kiota.Models.ServiceType? SrvType { get; set; }
#nullable restore
#else
        public global::Vorn.Tamin.Kiota.Models.ServiceType SrvType { get; set; }
#endif
        /// <summary>If BEHDASHT.thritha is sent, service code follows Ministry of Health coding.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Terminology { get; set; }
#nullable restore
#else
        public string Terminology { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Vorn.Tamin.Kiota.Models.Service"/> and sets the default values.
        /// </summary>
        public Service()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Vorn.Tamin.Kiota.Models.Service"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Vorn.Tamin.Kiota.Models.Service CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Vorn.Tamin.Kiota.Models.Service();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "parTarefGrp", n => { ParTarefGrp = n.GetObjectValue<global::Vorn.Tamin.Kiota.Models.ParTarefGroup>(global::Vorn.Tamin.Kiota.Models.ParTarefGroup.CreateFromDiscriminatorValue); } },
                { "srvCode", n => { SrvCode = n.GetStringValue(); } },
                { "srvCodeComplete", n => { SrvCodeComplete = n.GetStringValue(); } },
                { "srvId", n => { SrvId = n.GetIntValue(); } },
                { "srvName", n => { SrvName = n.GetStringValue(); } },
                { "srvType", n => { SrvType = n.GetObjectValue<global::Vorn.Tamin.Kiota.Models.ServiceType>(global::Vorn.Tamin.Kiota.Models.ServiceType.CreateFromDiscriminatorValue); } },
                { "terminology", n => { Terminology = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Vorn.Tamin.Kiota.Models.ParTarefGroup>("parTarefGrp", ParTarefGrp);
            writer.WriteStringValue("srvCode", SrvCode);
            writer.WriteStringValue("srvCodeComplete", SrvCodeComplete);
            writer.WriteIntValue("srvId", SrvId);
            writer.WriteStringValue("srvName", SrvName);
            writer.WriteObjectValue<global::Vorn.Tamin.Kiota.Models.ServiceType>("srvType", SrvType);
            writer.WriteStringValue("terminology", Terminology);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
