// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
using Vorn.Tamin.Kiota.Sandbox.Api.V2.WsDentistBase.FindDentistServiceNameByTooth.Item;
namespace Vorn.Tamin.Kiota.Sandbox.Api.V2.WsDentistBase.FindDentistServiceNameByTooth
{
    /// <summary>
    /// Builds and executes requests for operations under \api\v2\ws-dentist-base\find-dentist-service-name-by-tooth
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class FindDentistServiceNameByToothRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the Vorn.Tamin.Kiota.Sandbox.api.v2.wsDentistBase.findDentistServiceNameByTooth.item collection</summary>
        /// <param name="position">Selected tooth FDI code</param>
        /// <returns>A <see cref="global::Vorn.Tamin.Kiota.Sandbox.Api.V2.WsDentistBase.FindDentistServiceNameByTooth.Item.WithSelectedToothItemRequestBuilder"/></returns>
        public global::Vorn.Tamin.Kiota.Sandbox.Api.V2.WsDentistBase.FindDentistServiceNameByTooth.Item.WithSelectedToothItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("selectedTooth", position);
                return new global::Vorn.Tamin.Kiota.Sandbox.Api.V2.WsDentistBase.FindDentistServiceNameByTooth.Item.WithSelectedToothItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Vorn.Tamin.Kiota.Sandbox.Api.V2.WsDentistBase.FindDentistServiceNameByTooth.FindDentistServiceNameByToothRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public FindDentistServiceNameByToothRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/v2/ws-dentist-base/find-dentist-service-name-by-tooth", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Vorn.Tamin.Kiota.Sandbox.Api.V2.WsDentistBase.FindDentistServiceNameByTooth.FindDentistServiceNameByToothRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public FindDentistServiceNameByToothRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/v2/ws-dentist-base/find-dentist-service-name-by-tooth", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
