// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Vorn.Tamin.Kiota.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class NoteDetailsReferral : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The complaints property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Vorn.Tamin.Kiota.Models.Complaint>? Complaints { get; set; }
#nullable restore
#else
        public List<global::Vorn.Tamin.Kiota.Models.Complaint> Complaints { get; set; }
#endif
        /// <summary>The docSpecReferred property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Vorn.Tamin.Kiota.Models.Special? DocSpecReferred { get; set; }
#nullable restore
#else
        public global::Vorn.Tamin.Kiota.Models.Special DocSpecReferred { get; set; }
#endif
        /// <summary>The icd10s property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Vorn.Tamin.Kiota.Models.Icd10>? Icd10s { get; set; }
#nullable restore
#else
        public List<global::Vorn.Tamin.Kiota.Models.Icd10> Icd10s { get; set; }
#endif
        /// <summary>The id property</summary>
        public long? Id { get; set; }
        /// <summary>The masterChild property</summary>
        public long? MasterChild { get; set; }
        /// <summary>The masterParent property</summary>
        public long? MasterParent { get; set; }
        /// <summary>The message property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Message { get; set; }
#nullable restore
#else
        public string Message { get; set; }
#endif
        /// <summary>The patientNationalCode property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PatientNationalCode { get; set; }
#nullable restore
#else
        public string PatientNationalCode { get; set; }
#endif
        /// <summary>The quantity property</summary>
        public int? Quantity { get; set; }
        /// <summary>The referralHijriDate property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ReferralHijriDate { get; set; }
#nullable restore
#else
        public string ReferralHijriDate { get; set; }
#endif
        /// <summary>Required for hospitalization-order prescriptions.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? SiamId { get; set; }
#nullable restore
#else
        public string SiamId { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Vorn.Tamin.Kiota.Models.NoteDetailsReferral"/> and sets the default values.
        /// </summary>
        public NoteDetailsReferral()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Vorn.Tamin.Kiota.Models.NoteDetailsReferral"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Vorn.Tamin.Kiota.Models.NoteDetailsReferral CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Vorn.Tamin.Kiota.Models.NoteDetailsReferral();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "complaints", n => { Complaints = n.GetCollectionOfObjectValues<global::Vorn.Tamin.Kiota.Models.Complaint>(global::Vorn.Tamin.Kiota.Models.Complaint.CreateFromDiscriminatorValue)?.AsList(); } },
                { "docSpecReferred", n => { DocSpecReferred = n.GetObjectValue<global::Vorn.Tamin.Kiota.Models.Special>(global::Vorn.Tamin.Kiota.Models.Special.CreateFromDiscriminatorValue); } },
                { "icd10s", n => { Icd10s = n.GetCollectionOfObjectValues<global::Vorn.Tamin.Kiota.Models.Icd10>(global::Vorn.Tamin.Kiota.Models.Icd10.CreateFromDiscriminatorValue)?.AsList(); } },
                { "id", n => { Id = n.GetLongValue(); } },
                { "masterChild", n => { MasterChild = n.GetLongValue(); } },
                { "masterParent", n => { MasterParent = n.GetLongValue(); } },
                { "message", n => { Message = n.GetStringValue(); } },
                { "patientNationalCode", n => { PatientNationalCode = n.GetStringValue(); } },
                { "quantity", n => { Quantity = n.GetIntValue(); } },
                { "referralHijriDate", n => { ReferralHijriDate = n.GetStringValue(); } },
                { "siamId", n => { SiamId = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteCollectionOfObjectValues<global::Vorn.Tamin.Kiota.Models.Complaint>("complaints", Complaints);
            writer.WriteObjectValue<global::Vorn.Tamin.Kiota.Models.Special>("docSpecReferred", DocSpecReferred);
            writer.WriteCollectionOfObjectValues<global::Vorn.Tamin.Kiota.Models.Icd10>("icd10s", Icd10s);
            writer.WriteLongValue("id", Id);
            writer.WriteLongValue("masterChild", MasterChild);
            writer.WriteLongValue("masterParent", MasterParent);
            writer.WriteStringValue("message", Message);
            writer.WriteStringValue("patientNationalCode", PatientNationalCode);
            writer.WriteIntValue("quantity", Quantity);
            writer.WriteStringValue("referralHijriDate", ReferralHijriDate);
            writer.WriteStringValue("siamId", SiamId);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
