// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Vorn.Tamin.Kiota.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class ReferralCartableItem : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The docID property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? DocID { get; set; }
#nullable restore
#else
        public string DocID { get; set; }
#endif
        /// <summary>The firstName property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? FirstName { get; set; }
#nullable restore
#else
        public string FirstName { get; set; }
#endif
        /// <summary>The lastName property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? LastName { get; set; }
#nullable restore
#else
        public string LastName { get; set; }
#endif
        /// <summary>The masterChild property</summary>
        public long? MasterChild { get; set; }
        /// <summary>The noteHeadId property</summary>
        public long? NoteHeadId { get; set; }
        /// <summary>The patientID property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PatientID { get; set; }
#nullable restore
#else
        public string PatientID { get; set; }
#endif
        /// <summary>The prescDate property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PrescDate { get; set; }
#nullable restore
#else
        public string PrescDate { get; set; }
#endif
        /// <summary>The prescType property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Vorn.Tamin.Kiota.Models.PrescType? PrescType { get; set; }
#nullable restore
#else
        public global::Vorn.Tamin.Kiota.Models.PrescType PrescType { get; set; }
#endif
        /// <summary>The referralDate property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Vorn.Tamin.Kiota.Models.ReferralCartableItem.ReferralCartableItem_referralDate? ReferralDate { get; set; }
#nullable restore
#else
        public global::Vorn.Tamin.Kiota.Models.ReferralCartableItem.ReferralCartableItem_referralDate ReferralDate { get; set; }
#endif
        /// <summary>The referralId property</summary>
        public long? ReferralId { get; set; }
        /// <summary>The specCodeReferral property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? SpecCodeReferral { get; set; }
#nullable restore
#else
        public string SpecCodeReferral { get; set; }
#endif
        /// <summary>The specCodeReferred property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? SpecCodeReferred { get; set; }
#nullable restore
#else
        public string SpecCodeReferred { get; set; }
#endif
        /// <summary>The specDescReferral property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? SpecDescReferral { get; set; }
#nullable restore
#else
        public string SpecDescReferral { get; set; }
#endif
        /// <summary>The specDescReferred property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? SpecDescReferred { get; set; }
#nullable restore
#else
        public string SpecDescReferred { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Vorn.Tamin.Kiota.Models.ReferralCartableItem"/> and sets the default values.
        /// </summary>
        public ReferralCartableItem()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Vorn.Tamin.Kiota.Models.ReferralCartableItem"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Vorn.Tamin.Kiota.Models.ReferralCartableItem CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Vorn.Tamin.Kiota.Models.ReferralCartableItem();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "docID", n => { DocID = n.GetStringValue(); } },
                { "firstName", n => { FirstName = n.GetStringValue(); } },
                { "lastName", n => { LastName = n.GetStringValue(); } },
                { "masterChild", n => { MasterChild = n.GetLongValue(); } },
                { "noteHeadId", n => { NoteHeadId = n.GetLongValue(); } },
                { "patientID", n => { PatientID = n.GetStringValue(); } },
                { "prescDate", n => { PrescDate = n.GetStringValue(); } },
                { "prescType", n => { PrescType = n.GetObjectValue<global::Vorn.Tamin.Kiota.Models.PrescType>(global::Vorn.Tamin.Kiota.Models.PrescType.CreateFromDiscriminatorValue); } },
                { "referralDate", n => { ReferralDate = n.GetObjectValue<global::Vorn.Tamin.Kiota.Models.ReferralCartableItem.ReferralCartableItem_referralDate>(global::Vorn.Tamin.Kiota.Models.ReferralCartableItem.ReferralCartableItem_referralDate.CreateFromDiscriminatorValue); } },
                { "referralId", n => { ReferralId = n.GetLongValue(); } },
                { "specCodeReferral", n => { SpecCodeReferral = n.GetStringValue(); } },
                { "specCodeReferred", n => { SpecCodeReferred = n.GetStringValue(); } },
                { "specDescReferral", n => { SpecDescReferral = n.GetStringValue(); } },
                { "specDescReferred", n => { SpecDescReferred = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("docID", DocID);
            writer.WriteStringValue("firstName", FirstName);
            writer.WriteStringValue("lastName", LastName);
            writer.WriteLongValue("masterChild", MasterChild);
            writer.WriteLongValue("noteHeadId", NoteHeadId);
            writer.WriteStringValue("patientID", PatientID);
            writer.WriteStringValue("prescDate", PrescDate);
            writer.WriteObjectValue<global::Vorn.Tamin.Kiota.Models.PrescType>("prescType", PrescType);
            writer.WriteObjectValue<global::Vorn.Tamin.Kiota.Models.ReferralCartableItem.ReferralCartableItem_referralDate>("referralDate", ReferralDate);
            writer.WriteLongValue("referralId", ReferralId);
            writer.WriteStringValue("specCodeReferral", SpecCodeReferral);
            writer.WriteStringValue("specCodeReferred", SpecCodeReferred);
            writer.WriteStringValue("specDescReferral", SpecDescReferral);
            writer.WriteStringValue("specDescReferred", SpecDescReferred);
            writer.WriteAdditionalData(AdditionalData);
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="long"/>, <see cref="string"/>
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class ReferralCartableItem_referralDate : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type <see cref="long"/></summary>
            public long? Int64 { get; set; }
            /// <summary>Composed type representation for type <see cref="string"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public string? String { get; set; }
#nullable restore
#else
            public string String { get; set; }
#endif
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::Vorn.Tamin.Kiota.Models.ReferralCartableItem.ReferralCartableItem_referralDate"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::Vorn.Tamin.Kiota.Models.ReferralCartableItem.ReferralCartableItem_referralDate CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
                var mappingValue = parseNode.GetChildNode("")?.GetStringValue();
                var result = new global::Vorn.Tamin.Kiota.Models.ReferralCartableItem.ReferralCartableItem_referralDate();
                if(parseNode.GetLongValue() is long int64Value)
                {
                    result.Int64 = int64Value;
                }
                else if(parseNode.GetStringValue() is string stringValue)
                {
                    result.String = stringValue;
                }
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
                if(Int64 != null)
                {
                    writer.WriteLongValue(null, Int64);
                }
                else if(String != null)
                {
                    writer.WriteStringValue(null, String);
                }
            }
        }
    }
}
#pragma warning restore CS0618
