// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Vorn.Tamin.Kiota.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum RefreshTokenV2Request_grant_type
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "refresh_token")]
        #pragma warning disable CS1591
        Refresh_token,
        #pragma warning restore CS1591
        [EnumMember(Value = "token_refresh")]
        #pragma warning disable CS1591
        Token_refresh,
        #pragma warning restore CS1591
    }
}
