// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
using Vorn.Tamin.Kiota.Interface.Epresc.SendEpresc.V2.FindDentistServiceNameByTooth.Item.Item;
namespace Vorn.Tamin.Kiota.Interface.Epresc.SendEpresc.V2.FindDentistServiceNameByTooth.Item
{
    /// <summary>
    /// Builds and executes requests for operations under \interface\epresc\SendEpresc\v2\find-dentist-service-name-by-tooth\{selectedTooth}
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class WithSelectedToothItemRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the Vorn.Tamin.Kiota.interface.epresc.SendEpresc.v2.findDentistServiceNameByTooth.item.item collection</summary>
        /// <param name="position">Patient national code</param>
        /// <returns>A <see cref="global::Vorn.Tamin.Kiota.Interface.Epresc.SendEpresc.V2.FindDentistServiceNameByTooth.Item.Item.WithPatientItemRequestBuilder"/></returns>
        public global::Vorn.Tamin.Kiota.Interface.Epresc.SendEpresc.V2.FindDentistServiceNameByTooth.Item.Item.WithPatientItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("patientId", position);
                return new global::Vorn.Tamin.Kiota.Interface.Epresc.SendEpresc.V2.FindDentistServiceNameByTooth.Item.Item.WithPatientItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Vorn.Tamin.Kiota.Interface.Epresc.SendEpresc.V2.FindDentistServiceNameByTooth.Item.WithSelectedToothItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithSelectedToothItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/interface/epresc/SendEpresc/v2/find-dentist-service-name-by-tooth/{selectedTooth}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Vorn.Tamin.Kiota.Interface.Epresc.SendEpresc.V2.FindDentistServiceNameByTooth.Item.WithSelectedToothItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithSelectedToothItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/interface/epresc/SendEpresc/v2/find-dentist-service-name-by-tooth/{selectedTooth}", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
