// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Microsoft.Kiota.Serialization.Form;
using Microsoft.Kiota.Serialization.Json;
using Microsoft.Kiota.Serialization.Multipart;
using Microsoft.Kiota.Serialization.Text;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
using Vorn.Tamin.Kiota.Sandbox.Api;
using Vorn.Tamin.Kiota.Sandbox.Auth;
using Vorn.Tamin.Kiota.Sandbox.Ep;
namespace Vorn.Tamin.Kiota.Sandbox
{
    /// <summary>
    /// The main entry point of the SDK, exposes the configuration and the fluent API.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class TaminKiotaSandboxClient : BaseRequestBuilder
    {
        /// <summary>The api property</summary>
        public global::Vorn.Tamin.Kiota.Sandbox.Api.ApiRequestBuilder Api
        {
            get => new global::Vorn.Tamin.Kiota.Sandbox.Api.ApiRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The auth property</summary>
        public global::Vorn.Tamin.Kiota.Sandbox.Auth.AuthRequestBuilder Auth
        {
            get => new global::Vorn.Tamin.Kiota.Sandbox.Auth.AuthRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The ep property</summary>
        public global::Vorn.Tamin.Kiota.Sandbox.Ep.EpRequestBuilder Ep
        {
            get => new global::Vorn.Tamin.Kiota.Sandbox.Ep.EpRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Vorn.Tamin.Kiota.Sandbox.TaminKiotaSandboxClient"/> and sets the default values.
        /// </summary>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public TaminKiotaSandboxClient(IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}", new Dictionary<string, object>())
        {
            ApiClientBuilder.RegisterDefaultSerializer<JsonSerializationWriterFactory>();
            ApiClientBuilder.RegisterDefaultSerializer<TextSerializationWriterFactory>();
            ApiClientBuilder.RegisterDefaultSerializer<FormSerializationWriterFactory>();
            ApiClientBuilder.RegisterDefaultSerializer<MultipartSerializationWriterFactory>();
            ApiClientBuilder.RegisterDefaultDeserializer<JsonParseNodeFactory>();
            ApiClientBuilder.RegisterDefaultDeserializer<TextParseNodeFactory>();
            ApiClientBuilder.RegisterDefaultDeserializer<FormParseNodeFactory>();
            if (string.IsNullOrEmpty(RequestAdapter.BaseUrl))
            {
                RequestAdapter.BaseUrl = "https://ep-test.tamin.ir";
            }
            PathParameters.TryAdd("baseurl", RequestAdapter.BaseUrl);
        }
    }
}
#pragma warning restore CS0618
