// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
using Vorn.Tamin.Kiota.Sandbox.Api.NoteDetailsReferral.Forward.Item;
namespace Vorn.Tamin.Kiota.Sandbox.Api.NoteDetailsReferral.Forward
{
    /// <summary>
    /// Builds and executes requests for operations under \api\noteDetailsReferral\forward
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ForwardRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the Vorn.Tamin.Kiota.Sandbox.api.noteDetailsReferral.forward.item collection</summary>
        /// <param name="position">Registered referral ID</param>
        /// <returns>A <see cref="global::Vorn.Tamin.Kiota.Sandbox.Api.NoteDetailsReferral.Forward.Item.WithReferralItemRequestBuilder"/></returns>
        public global::Vorn.Tamin.Kiota.Sandbox.Api.NoteDetailsReferral.Forward.Item.WithReferralItemRequestBuilder this[long position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("referralId", position);
                return new global::Vorn.Tamin.Kiota.Sandbox.Api.NoteDetailsReferral.Forward.Item.WithReferralItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>Gets an item from the Vorn.Tamin.Kiota.Sandbox.api.noteDetailsReferral.forward.item collection</summary>
        /// <param name="position">Registered referral ID</param>
        /// <returns>A <see cref="global::Vorn.Tamin.Kiota.Sandbox.Api.NoteDetailsReferral.Forward.Item.WithReferralItemRequestBuilder"/></returns>
        [Obsolete("This indexer is deprecated and will be removed in the next major version. Use the one with the typed parameter instead.")]
        public global::Vorn.Tamin.Kiota.Sandbox.Api.NoteDetailsReferral.Forward.Item.WithReferralItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                if (!string.IsNullOrWhiteSpace(position)) urlTplParams.Add("referralId", position);
                return new global::Vorn.Tamin.Kiota.Sandbox.Api.NoteDetailsReferral.Forward.Item.WithReferralItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Vorn.Tamin.Kiota.Sandbox.Api.NoteDetailsReferral.Forward.ForwardRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ForwardRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/noteDetailsReferral/forward", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Vorn.Tamin.Kiota.Sandbox.Api.NoteDetailsReferral.Forward.ForwardRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ForwardRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/noteDetailsReferral/forward", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
