// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
using Vorn.Tamin.Kiota.Interface.Epresc.SendEpresc.V2.FetchReferralCartable.Item;
namespace Vorn.Tamin.Kiota.Interface.Epresc.SendEpresc.V2.FetchReferralCartable
{
    /// <summary>
    /// Builds and executes requests for operations under \interface\epresc\SendEpresc\v2\fetchReferralCartable
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class FetchReferralCartableRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the Vorn.Tamin.Kiota.interface.epresc.SendEpresc.v2.fetchReferralCartable.item collection</summary>
        /// <param name="position">Doctor national code</param>
        /// <returns>A <see cref="global::Vorn.Tamin.Kiota.Interface.Epresc.SendEpresc.V2.FetchReferralCartable.Item.WithDocNationalCodeItemRequestBuilder"/></returns>
        public global::Vorn.Tamin.Kiota.Interface.Epresc.SendEpresc.V2.FetchReferralCartable.Item.WithDocNationalCodeItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("docNationalCode", position);
                return new global::Vorn.Tamin.Kiota.Interface.Epresc.SendEpresc.V2.FetchReferralCartable.Item.WithDocNationalCodeItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Vorn.Tamin.Kiota.Interface.Epresc.SendEpresc.V2.FetchReferralCartable.FetchReferralCartableRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public FetchReferralCartableRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/interface/epresc/SendEpresc/v2/fetchReferralCartable", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Vorn.Tamin.Kiota.Interface.Epresc.SendEpresc.V2.FetchReferralCartable.FetchReferralCartableRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public FetchReferralCartableRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/interface/epresc/SendEpresc/v2/fetchReferralCartable", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
