// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Vorn.Tamin.Kiota.Sandbox.Models
{
    /// <summary>
    /// application/x-www-form-urlencoded token request.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class AuthorizationCodeTokenRequest : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The client_id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ClientId { get; set; }
#nullable restore
#else
        public string ClientId { get; set; }
#endif
        /// <summary>The code property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Code { get; set; }
#nullable restore
#else
        public string Code { get; set; }
#endif
        /// <summary>The code_verifier property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CodeVerifier { get; set; }
#nullable restore
#else
        public string CodeVerifier { get; set; }
#endif
        /// <summary>The PDF prose uses code_authorization/type_grant; cURL examples use authorization_code/grant_type.</summary>
        public global::Vorn.Tamin.Kiota.Sandbox.Models.AuthorizationCodeTokenRequest_grant_type? GrantType { get; set; }
        /// <summary>The redirect_uri property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? RedirectUri { get; set; }
#nullable restore
#else
        public string RedirectUri { get; set; }
#endif
        /// <summary>Alias name used in older prose.</summary>
        [Obsolete("")]
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? VerifierCode { get; set; }
#nullable restore
#else
        public string VerifierCode { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Vorn.Tamin.Kiota.Sandbox.Models.AuthorizationCodeTokenRequest"/> and sets the default values.
        /// </summary>
        public AuthorizationCodeTokenRequest()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Vorn.Tamin.Kiota.Sandbox.Models.AuthorizationCodeTokenRequest"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Vorn.Tamin.Kiota.Sandbox.Models.AuthorizationCodeTokenRequest CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Vorn.Tamin.Kiota.Sandbox.Models.AuthorizationCodeTokenRequest();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "client_id", n => { ClientId = n.GetStringValue(); } },
                { "code", n => { Code = n.GetStringValue(); } },
                { "code_verifier", n => { CodeVerifier = n.GetStringValue(); } },
                { "grant_type", n => { GrantType = n.GetEnumValue<global::Vorn.Tamin.Kiota.Sandbox.Models.AuthorizationCodeTokenRequest_grant_type>(); } },
                { "redirect_uri", n => { RedirectUri = n.GetStringValue(); } },
                { "verifier_code", n => { VerifierCode = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("client_id", ClientId);
            writer.WriteStringValue("code", Code);
            writer.WriteStringValue("code_verifier", CodeVerifier);
            writer.WriteEnumValue<global::Vorn.Tamin.Kiota.Sandbox.Models.AuthorizationCodeTokenRequest_grant_type>("grant_type", GrantType);
            writer.WriteStringValue("redirect_uri", RedirectUri);
            writer.WriteStringValue("verifier_code", VerifierCode);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
