// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Vorn.Tamin.Kiota.Sandbox.Models
{
    /// <summary>The PDF prose uses code_authorization/type_grant; cURL examples use authorization_code/grant_type.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum AuthorizationCodeTokenRequest_grant_type
    {
        [EnumMember(Value = "authorization_code")]
        #pragma warning disable CS1591
        Authorization_code,
        #pragma warning restore CS1591
        [EnumMember(Value = "code_authorization")]
        #pragma warning disable CS1591
        Code_authorization,
        #pragma warning restore CS1591
    }
}
