// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Vorn.Tamin.Kiota.Sandbox.Models
{
    /// <summary>000 unspecified, 001 pathology, 002 genetics, 003 global genetics, 004 medical diagnosis</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum ParTarefGroup_parGrpCode
    {
        [EnumMember(Value = "000")]
        #pragma warning disable CS1591
        ZeroZeroZero,
        #pragma warning restore CS1591
        [EnumMember(Value = "001")]
        #pragma warning disable CS1591
        ZeroZeroOne,
        #pragma warning restore CS1591
        [EnumMember(Value = "002")]
        #pragma warning disable CS1591
        ZeroZeroTwo,
        #pragma warning restore CS1591
        [EnumMember(Value = "003")]
        #pragma warning disable CS1591
        ZeroZeroThree,
        #pragma warning restore CS1591
        [EnumMember(Value = "004")]
        #pragma warning disable CS1591
        ZeroZeroFour,
        #pragma warning restore CS1591
    }
}
